image: docker:stable

services:
  - docker:stable-dind

variables:
  REPOSITORY: "aparapi/aparapi"
  VERSION: "2.0.0"
  DOCKER_HOST: "tcp://localhost:2375"

before_script:
  - echo "${DOCKER_TOKEN}" | docker login --username "${DOCKER_USER}" --password-stdin

stages:
   - opencl

.opencl_template: &opencl_definition
    stage: opencl
    script:
      - if [ $CI_COMMIT_REF_NAME == "develop" ]; then
          REV="git";
        elif [ $CI_COMMIT_REF_NAME == "master" ]; then
          REV="latest";
        else
          REV="$CI_COMMIT_REF_NAME";
        fi
      - docker pull "${REPOSITORY}-nvidia:${REV}" || true
      - docker build --network=host --pull -t "${REPOSITORY}-nvidia:${REV}"
                     --cache-from "${REPOSITORY}-nvidia:${REV}"
                     --build-arg "aparapiver=${VERSION}"
                     "nvidia/"
      - docker pull "${REPOSITORY}-amdgpu:${REV}" || true
      - docker build --network=host --pull -t "${REPOSITORY}-amdgpu:${REV}"
                     --cache-from "${REPOSITORY}-amdgpu:${REV}"
                     --build-arg "aparapiver=${VERSION}"
                     "amdgpu/"
      - docker push "${REPOSITORY}-nvidia"
      - docker push "${REPOSITORY}-amdgpu"
    only:
      - master
      - develop
      - tags
    tags:
      - dind

opencl:
    <<: *opencl_definition
